### ISSUE TITLE
error in Domoticz

### ISSUE THREAD

**Issue by pfolcato** [Chouteau49/Domoticz_Tapo_TP-Link#1]
hello, thnx for the plugin but I have this error when I try to installa this plugin:

 2023-12-26 15:37:58.870 Error: Tapo: (tapo_tp-link) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/Domoticz_Tapo_TP-Link/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.7/dist-packages'.
2023-12-26 15:37:58.878 Error: Tapo: Traceback (most recent call last):
2023-12-26 15:37:58.878 Error: Tapo: File "/home/pi/domoticz/plugins/Domoticz_Tapo_TP-Link/plugin.py", line 45, in <module>
2023-12-26 15:37:58.878 Error: Tapo: from PyP100 import PyP100
2023-12-26 15:37:58.878 Error: Tapo: File "/home/pi/domoticz/plugins/Domoticz_Tapo_TP-Link/PyP100/PyP100.py", line 9, in <module>
2023-12-26 15:37:58.878 Error: Tapo: from Crypto.Cipher import AES, PKCS1_OAEP, PKCS1_v1_5
2023-12-26 15:37:58.878 Error: Tapo: File "/home/pi/domoticz/plugins/Domoticz_Tapo_TP-Link/Crypto/Cipher/__init__.py", line 27, in <module>
2023-12-26 15:37:58.878 Error: Tapo: from Crypto.Cipher._mode_ecb import _create_ecb_cipher
2023-12-26 15:37:58.878 Error: Tapo: File "/home/pi/domoticz/plugins/Domoticz_Tapo_TP-Link/Crypto/Cipher/_mode_ecb.py", line 47, in <module>
2023-12-26 15:37:58.878 Error: Tapo: """
2023-12-26 15:37:58.878 Error: Tapo: File "/home/pi/domoticz/plugins/Domoticz_Tapo_TP-Link/Crypto/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
2023-12-26 15:37:58.878 Error: Tapo: raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
2023-12-26 15:37:58.878 Error: Tapo: OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Not found '_raw_ecb.cpython-37m-arm-linux-gnueabihf.so', Cannot load '_raw_ecb.abi3.so': cannot load library '/home/pi/domoticz/plugins/Domoticz_Tapo_TP-Link/Crypto/Util/../Cipher/_raw_ecb.abi3.so': /home/pi/domoticz/plugins/Domoticz_Tapo_TP-Link/Crypto/Util/../Cipher/_raw_ecb.abi3.so: wrong ELF class: ELFCLASS64. Additionally, ctypes.util.find_library() did not manage to locate a library called '/home/pi/domoticz/plugins/Domoticz_Tapo_TP-Link/Crypto/Util/../Cipher/_raw_ecb.abi3.so', Not found '_raw_ecb.so' 

I have the Tapo P110 hardware but now still not working on domoticz.... I try to update Cryptodome, pycryptodome, pycrypto, cryptography, rustc, tokenizers, PyP100... without success... 
Can yuo explain me what I'm wrong?

**Comment by Chouteau49** [comment]
Bonjour,

Je suis passé sur home assistant avec le plugin TPLink.
Je n'utilise plus Domoticz.
